### ISSUE TITLE
how to use it with https proxies in win32?

### ISSUE THREAD

**Issue by xq3584123** [SUP3RIA/Atlantr#6]
Thanks very much for providing this great program
i download Atr3_win32 but i just don't know how to use it with https/sock4 or 5 proxies in Windows.
i know if single ip requests frequently, ip will get blocked.
Can you leave a email so that i can get in touch you!

**Comment by SUP3RIA** [comment]
Just run Linux in a VM und use proxychains or fork it and implement it your self. Gevent is also faster on Linux.

**Comment by ghost** [comment]
There is no feature added to select proxies in the tool itself; mainly because this would run slow.
I recommend, as above running a Linux server (CentOS/Debian) -> install proxychains and run the python script on that server; you can check your proxy chain with:
``$ proxychains4 curl ipinfo.io/ip``
If configured correctly you can chain as much proxies as you want to use for ATR3.

You are on Windows, probably for a reason. I do not recommend searching for tools to proxychain Windows.
 You could install VMWare and download a popular ISO like Kali;
https://www.youtube.com/watch?v=kt_C9RW_ttA has a great tutorial!

Regards

**Comment by ghost** [comment]
@SUP3RIA Close?
